
                                          ExceptionHandling(30mins)


Q 1 
What will the following code print?
public class Test
{
           public int luckyNumber(int seed)
	{
		if(seed > 10) return seed%10;
		int x = 0;
		try
		{
			if(seed%2 == 0) throw new Exception("No Even no.");
			else return x;
		}
		catch(Exception e)
		{
			return 3;
		}
		finally
		{
			return 7;
		}
	}
	public static void main(String args[])
	{
		int amount = 100, seed = 6;
		switch( new Test().luckyNumber(6) )
		{
			case 3: amount = amount * 2;
			case 7: amount = amount * 2;
			case 6: amount = amount + amount;
 			default :
		}
		System.out.println(amount);
	}
}
A.	It will not compile.
B.	It will throw an exception at runtime.
C.	It will print 800
D.	It will print 200
E.	It will print  400

Ans:E

Q 2 Identify the correct constructs.
Select 1 Option
A.
try {
  for( ;; );
}finally { }

B.
try {
  File f = new File("c:\a.txt");
} catch {  f = null; }

C.
int k = o
try {
  k = callValidMethod();
} 
System.out.println(k);
catch {  k = -1; }

D.
try {
  try {
     Socket s = new ServerSocket(3030);
  }catch(Exception e) { 
    s = new ServerSocket(4040);
  } 
}

E.
try {
       s = new ServerSocket(3030); 
} catch(Exception t){ t.printStackTrace(); }
} catch(IOException e) {
    s = new ServerSocket(4040);
} catch(Throwable t){ t.printStackTrace(); }

F.
int x = validMethod();
try {
  if(x == 5) throw new IOException();
  else if(x == 6) throw new Exception();
}finally {
 x = 8;
}
catch(Exception e){ x = 9; }

Ans:A

Q3
Consider the following code ... 
class A 
{
    public void doA(int k) throws Exception { // 0
        for(int i=0; i< 10; i++) {
            if(i == k) throw new Exception("Index of k is "+i); // 1
        }
    }
    public void doB(boolean f) { //2
        if(f) {
            doA(15); //3
        }
        else return;
    }
    public static void main(String[] args) { //4
        A a = new A();
        a.doB(args.length>0); //5
    }
}
Which of the following statements are correct? 

Please select 1 option.
A.	This will compile and run without any errors or exception.
B.	This will compile if 'throws Exception' is added at line //2
C.	This will compile if 'throws Exception' is added at line //4
D.	This will compile if 'throws Exception' is added at line //2 as well as //4
E.	This will compile if  line marked // 0 is enclosed in a try - catch block.

Ans:D


Q4 
What is the result of compiling and running this code?
class MyException extends Throwable{}
class MyException1 extends MyException{}
class MyException2 extends MyException{}
class MyException3 extends MyException2{}
public class ExceptionTest
{
	void myMethod() throws MyException
	{
		throw new MyException3();
	}
	public static void main(String[] args)
	{
		ExceptionTest et = new ExceptionTest();
		try
		{
			et.myMethod();
		}
		catch(MyException me)
		{
			System.out.println("MyException thrown");
		}
		catch(MyException3 me3)
		{
			System.out.println("MyException3 thrown");
		}
		finally
		{
			System.out.println(" Done");
		}
	}
}

Please select 1 option
A.	MyException thrown
B.	MyException3 thrown
C.	MyException thrown Done
D.	MyException3 thrown Done
E.	It fails to compile

Ans:E


Q 5
Consider the following hierarchy of Exception classes :

	java.lang.RuntimeException
                                  +-------- IndexOutOfBoundsException
	                         +---------ArrayIndexOutOfBoundsException

Which of the following statements are correct for a method that can throw ArrayIndexOutOfBounds as well as StringIndexOutOfBounds Exceptions but does not have try catch blocks to catch the same?

Please select 3 options
A.	The method calling this method will either have to catch these 2 exceptions or declare them in it's throws clause.
B.	It is ok if it declares just 'throws ArrayIndexOutOfBoundsException'
C.	It must declare 'throws ArrayIndexOutOfBoundsException, StringIndexOutOfBoundsException'
D.	It is ok if it declares just 'throws IndexOutOfBoundsException'
E.	It does not need to declare any throws clause.

Ans:B,E and D


Q6
Consider the following code snippet:
void m1() throws Exception
{
   try
   {
      // line1
   }
   catch (IOException e)
   {
       throw new SQLException();
   }
   catch(SQLException e)
   {
       throw new InstantiationException();
   }
   finally
   {
      throw new CloneNotSupportedException()   // this is not a RuntimeException.
   }
}
Which of the following statements are true?

A.	If IOException gets thrown at line1, then the whole method will end up throwing SQLException.
B.	If IOException gets thrown at line1, then the whole method will end up throwing CloneNotSupportedException.
C.	If IOException gets thrown at line1, then the whole method will end up throwing InstantiationException()
D.	If no exception is thrown at line1, then the whole method will end up throwing CloneNotSupportedException.
E.	If SQLException gets thrown at line1, then the whole method will end up throwing InstantiationException()


Ans:B and D


Q7: What will following code print when run.?
public class Test
{
 static String s = "";
 public static void m0(int a, int b)
 {
   s +=a;
   m2();
   m1(b);
 }
 public static void m1(int i)
 {
   s += i;
 }
 public static void m2()
 {
  throw new NullPointerException("aa");
 }
 public static void m()
 {
   m0(1, 2);
   m1(3);
 }
 public static void main(String args[])
 {
   try
   {
    m();
   }
   catch(Exception e){ }
   System.out.println(s);
 }
}

A.	1
B.	12
C.	123
D.	2
E.	It will throw an exception at runtime.

Ans:A

Q8
Assume that a method named 'method1' contains code which may raise a non-runtime (checked) Exception.
What is the correct way to declare that method so that it indicates that it expects the caller to handle that exception?
Please select 2 options.
A.	public void method1() throws Throwable
B.	public void method1() throw Exception
C.	public void method1() throw new Exception
D.	public void method1() throws Exception
E.	public void method1()

Ans:A and c

Q9 : What will following code print when run.?
public class TestClass
{
   public static void main(String args[])
   {
      try{
         m1();
      }catch(IndexOutOfBoundsException e){
         System.out.println("1");
         throw new NullPointerException();
      }catch(NullPointerException e){
         System.out.println("2");
         return;
      }catch (Exception e) {
         System.out.println("3");
      }finally{
         System.out.println("4");
      }
      System.out.println("END");
   }
   // IndexOutOfBoundsException is a subclass of RuntimeException.
   static void m1()
   {
      System.out.println("m1 Starts");
      throw new IndexOutOfBoundsException( "Big Bang " );
   }
}
Select 3 correct options.

A.	The program will print 'm1 Starts'.
B.	The program will print 'm1 Starts', 1 and 4, in that order.
C.	The program will print 'm1 Starts', 1, 2 in that order.
D.	The program will print 'm1 Starts', 1, 2 and 4 in that order.
E.	'END' will not be printed.

Ans:A , B and E

Q10.
What will happen when the following program is compiled and run?

public class SM
{
    public String checkIt(String s)
    {
	if(s.length() == 0 || s == null)
	{
	    return "EMPTY";
	}
	else return "NOT EMPTY";
    }
    
    public static void main(String[] args)
    {
	SM a = new SM();
	a.check(null);
    }
   
}
Please select 1 correct option
A.	It will print EMPTY.
B.	It will print NOT EMPTY.
C.	It will throw NullPointerException.
D.	It will print EMPTY if || is replaced with |.

Ans:C

Q11
Given the following program, which of these statements are true?
public class FinallyTest
{
   public static void main(String args[])
   {
      try
      {
          if (args.length == 0) return;
          else throw new Exception("Some Exception");
      }
      catch(Exception e)
      {
          System.out.println("Exception in Main");
      }
      finally
      {
          System.out.println("The end");
      }
   }
}
Please select 2 correct options.
A.	If run with no arguments, the program will only print 'The end'.
B.	If run with one argument, the program will only print 'The end'.
C.	If run with one argument, the program will print 'Exception in Main' and 'The end'.
D.	If run with one argument, the program will only print 'Exception in Main'.
E.	Only one of the above is correct.

Ans:A and C

Q  12
What will be the output when the following code is compiled and run?
//in file Test.java
class E1 extends Exception{ }
class E2 extends E1 { }
class Test
{
	public static void main(String[] args)
	{
		try{
			throw new E2();
		}
		catch(E1 e){
			System.out.println("E1");
		}
		catch(Exception e){
			System.out.println("E");
		}
		finally{
			System.out.println("Finally");
		}
	}
}
Please select 1 option
A.	It will not compile.
B.	It will print E1 and Finally.
C.	It will print E1, E and Finally.
D.	It will print E and Finally.
E.	It will print Finally.

Ans:B

Q13
Which of these statements are true?
Please select 2 options.

A.	If a RuntimeException is not caught, the method will terminate and normal execution of the thread will resume.
B.	An overriding method must declare that it throws the same exception classes as the method it overrides.
C.	The main method of a program can declare that it throws checked exceptions.
D.	A method declaring that it throws a certain exception class may throw instances of any subclass of that exception class.
E.	finally blocks are executed if and only if an exception gets thrown while inside the corresponding try block.

Q 14
Given the class
// Filename: Test.java
public class Test
{
   public static void main(String args[])
   {
      for(int i = 0; i< args.length; i++)
      {
         System.out.print("  "+args[i]);
      }
   }
}
Now consider the following 3 options for running the program:
a: java Test
b: java Test param1
c: java Test param1 param2

Which of the following statements are true?
Please select 2 options
A.	The program will throw java.lang.ArrayIndexOutofBoundsException on option a.
B.	The program will throw java.lang.NullPointerException on option a.
C.	The program will print 'Test param1' on option b.
D.	It will print 'param1 param2' on option c.
E.	It will not print anything on option a.

Ans:C and D

Q15
What letters, and in what order, will be printed when the following program is compiled and run?
public class FinallyTest
{
   public static void main(String args[]) throws Exception
   {
       try
       {
          m1();
          System.out.println("A");
       }
       finally
       {
          System.out.println("B");
       }
       System.out.println("C");
   }
   public static void m1() throws Exception { throw new Exception(); }
}

Please select 1 option
A.	It will print C and B, in that order.
B.	It will print A and B, in that order.
C.	It will print B and throw Exception.
D.	It will print A, B and C in that order.
E.	Compile time error.


`Ans:C

